[project]
name = "thesis-cover"
description = "Creating a thesis cover"
authors = ["Sabrina Meindlhumer <sabrina.meindlhumer@protonmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
crop = "python crop.py"

[dependencies]
python = ">=3.12.4,<3.13"
numpy = ">=2.0.0,<2.1"
