[project]
name = "thesis-cover"
description = "Creating a thesis cover"
authors = ["Sabrina Meindlhumer <sabrina.meindlhumer@protonmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
process = { cmd = "python src/01_preprocess.py", inputs = [
    "images/pattern_raw.tif",
    "src/01_preprocess.py",
], outputs = [
    "images/pattern_cropped.tif",
] }
adapt = { cmd = "python src/02_adapt.py", depends-on = [
    "process",
], inputs = [
    "images/pattern_cropped.tif",
    "src/02_adapt.py",
] }

[dependencies]
python = ">=3.12.4,<3.13"
numpy = ">=2.0.0,<2.1"
scikit-image = ">=0.24.0,<0.25"
matplotlib = ">=3.9.1,<3.10"
